In [2]:
import numpy as np

In [3]:
from sklearn.datasets import load_iris

/Users/samitharanasinghe/opt/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
/Users/samitharanasinghe/opt/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/feature_extraction/image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [4]:
iris = load_iris()

/Users/samitharanasinghe/opt/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/datasets/base.py:242: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
/Users/samitharanasinghe/opt/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/datasets/base.py:246: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` 

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
X = iris.data

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from tensorflow.keras.utils import to_categorical

In [13]:
y = to_categorical(y)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
scaled_X_train = scaler_object.transform(X_train)

In [23]:
scaled_X_test = scaler_object.transform(X_test)

In [24]:
from tensorflow.keras.models import Sequential

In [25]:
from tensorflow.keras.layers import Dense

In [26]:
model = Sequential()

2023-02-18 15:41:52.186646: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [30]:
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.2196 - accuracy: 0.3500 - 519ms/epoch - 130ms/step
Epoch 2/150
4/4 - 0s - loss: 1.2063 - accuracy: 0.3500 - 5ms/epoch - 1ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1945 - accuracy: 0.3500 - 5ms/epoch - 1ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1835 - accuracy: 0.3500 - 5ms/epoch - 1ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1733 - accuracy: 0.3500 - 6ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1629 - accuracy: 0.3500 - 6ms/epoch - 1ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1536 - accuracy: 0.3500 - 7ms/epoch - 2ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1455 - accuracy: 0.3500 - 6ms/epoch - 1ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1382 - accuracy: 0.3500 - 8ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1297 - accuracy: 0.3500 - 6ms/epoch - 1ms/step
Epoch 11/150
4/4 - 0s - loss: 1.1215 - accuracy: 0.3500 - 7ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.1131 - accuracy: 0.3500 - 6ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.1050 - accuracy: 0.3500 -

Epoch 105/150
4/4 - 0s - loss: 0.4650 - accuracy: 0.8900 - 5ms/epoch - 1ms/step
Epoch 106/150
4/4 - 0s - loss: 0.4604 - accuracy: 0.9000 - 5ms/epoch - 1ms/step
Epoch 107/150
4/4 - 0s - loss: 0.4559 - accuracy: 0.9200 - 5ms/epoch - 1ms/step
Epoch 108/150
4/4 - 0s - loss: 0.4524 - accuracy: 0.9300 - 5ms/epoch - 1ms/step
Epoch 109/150
4/4 - 0s - loss: 0.4485 - accuracy: 0.9400 - 5ms/epoch - 1ms/step
Epoch 110/150
4/4 - 0s - loss: 0.4454 - accuracy: 0.9500 - 5ms/epoch - 1ms/step
Epoch 111/150
4/4 - 0s - loss: 0.4422 - accuracy: 0.9600 - 6ms/epoch - 2ms/step
Epoch 112/150
4/4 - 0s - loss: 0.4384 - accuracy: 0.9500 - 6ms/epoch - 1ms/step
Epoch 113/150
4/4 - 0s - loss: 0.4337 - accuracy: 0.9600 - 6ms/epoch - 1ms/step
Epoch 114/150
4/4 - 0s - loss: 0.4289 - accuracy: 0.9400 - 6ms/epoch - 1ms/step
Epoch 115/150
4/4 - 0s - loss: 0.4260 - accuracy: 0.9300 - 5ms/epoch - 1ms/step
Epoch 116/150
4/4 - 0s - loss: 0.4261 - accuracy: 0.9100 - 6ms/epoch - 1ms/step
Epoch 117/150
4/4 - 0s - loss: 0.4249 - 

In [37]:
predictions = model.predict(scaled_X_test)

2/2 [==============================] - 0s 2ms/step


In [38]:
predictions = predictions.argmax(axis=1)

In [40]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [41]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [42]:
print(confusion_matrix(y_test.argmax(axis=1),predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  0 16]]


In [43]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [44]:
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.98


In [45]:
model.save('myfirstmodel.h5')

In [46]:
from tensorflow.keras.models import load_model

In [47]:
new_model = load_model('myfirstmodel.h5')